# Generated by Django 5.1.5 on 2025-01-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirostagram', '0006_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.PositiveIntegerField(default=380, verbose_name='팔로워 수'),
        ),
    ]
