# Generated by Django 5.1.5 on 2025-01-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirostagram', '0007_alter_user_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/', verbose_name='이미지')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.PositiveIntegerField(default=101, verbose_name='팔로워 수'),
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='posts', to='pirostagram.image'),
        ),
    ]
