# Generated by Django 5.1.5 on 2025-01-20 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirostagram', '0008_image_remove_post_images_alter_user_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='pirostagram.post', verbose_name='게시글'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.PositiveIntegerField(default=488, verbose_name='팔로워 수'),
        ),
    ]
