# Generated by Django 5.1.5 on 2025-01-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirostagram', '0009_alter_like_post_alter_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.PositiveIntegerField(default=178, verbose_name='팔로워 수'),
        ),
    ]
