# Generated by Django 5.1.5 on 2025-01-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pirostagram', '0011_alter_user_followers_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.PositiveIntegerField(default=74, verbose_name='팔로워 수'),
        ),
    ]
