# Generated by Django 5.1.4 on 2025-01-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release', models.CharField(max_length=4)),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('DRAMA', 'Drama'), ('COMEDY', 'Comedy'), ('THRILLER', 'Thriller'), ('HORROR', 'Horror'), ('SCI_FI', 'Sci-Fi'), ('ROMANCE', 'Romance'), ('DOCUMENTARY', 'Documentary'), ('ANIMATION', 'Animation'), ('FANTASY', 'Fantasy'), ('MUSIC', 'Music'), ('MUSICAL', 'Musical')], default='ACTION', max_length=200)),
                ('age', models.CharField(choices=[('G', '전체'), ('PG', '12'), ('F15', '15'), ('R', '청불')], default='전체', max_length=200)),
                ('rate', models.CharField(max_length=200)),
                ('runningtime', models.CharField(max_length=200)),
                ('review', models.TextField()),
                ('director', models.CharField(max_length=200)),
                ('actor', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
