# Generated by Django 5.1.4 on 2025-01-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='age',
            field=models.CharField(choices=[('G', '전체'), ('PG', '12'), ('F15', '15'), ('R', '청불')], default='G', max_length=200),
        ),
    ]
