# Generated by Django 5.1.4 on 2025-01-15 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devtool', '0002_alter_devtool_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('image', models.ImageField(blank=True, upload_to='ideas/%Y%m%d', verbose_name='이미지')),
                ('content', models.TextField(verbose_name='설명')),
                ('interest', models.IntegerField(default=0, verbose_name='아이디어 관심도')),
                ('star', models.BooleanField(default=False, verbose_name='찜하기')),
                ('devtool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devtool.devtool', verbose_name='개발툴')),
            ],
        ),
    ]
