# Generated by Django 5.1.4 on 2025-01-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('kind', models.CharField(max_length=20, verbose_name='종류')),
                ('content', models.CharField(max_length=255, verbose_name='설명')),
            ],
        ),
    ]
